### PR TITLE
chore(deps): update AWS-SDK version to 2.1194.0 from 2.4.1.0

### PR DESCRIPTION
**Pull request by benheymink**
This updates the AWS-SDK dependency to 2.1194.0 (AWS SSO support was added in2.1093.0 - see https://twitter.com/ben11kehoe/status/1503739887371096067)

### CODE REVIEW

**Comment by benheymink** [comment]
Hmm...this actually doesn't seem to have fixed SSO support for me. Still likely worth absorbing for the SDK upgrade, but I'm still investigating how to get Dynamo-Easy to pick up an SSO profile from my `config` file.

**Comment by benheymink** [comment]
Have managed to get SSO access working via utilising https://github.com/benkehoe/aws-sso-credential-process. (This works with the current version of the AWS-SDK is use by dynamo-easy or the updated version included in this PR.)

**Comment by michaelwittwer** [comment]
@benheymink Since the [defined range](https://github.com/shiftcode/dynamo-easy/blob/master/package.json#L84) in `peerDependencies` already allows for any version above `2.401.0` there should no change be necessary to install newer versions of `aws-sdk` in your project. Glad to hear that it worked out for you. Closing the issue.

**Comment by benheymink** [comment]
Thanks. What's the status of this project by the way @michaelwittwer ? I notice no releases since 2020...is it still being actively maintained? Looking for a new home? Something else?

**Pull request closed without merging**
