### PR TITLE
feat: projectionExpression for single table batch get, scan and query

### PR DESCRIPTION
**Pull request by LeandroDG**

### CODE REVIEW

**Comment by michaelwittwer** [comment]
@LeandroDG Thanks for your contribution, really glad to see this. I had to disable one check (which only worked for PRs not coming from forks - never happened before because your PR is the first one coming from a new contributor 🎉and hopefully not the last one).

Coming back to you when I checked the code.

**Comment by LeandroDG** [comment]
Awesome Michael, thanks! Can't wait to remove the local install of the fork
and go back to working against the npm repo package :)

**Comment by michaelwittwer** [comment]
@LeandroDG during the review a few other things came up (see #243 for more infos), i will merge your code into a new branch as a base to also fix other stuff, will inform you when the work is done and ready to pull

**Comment by LeandroDG** [comment]
Awesome, thanks Michael!

**Pull request merged**
